version: "3"
services:
  www.blog.priv:
    image: "httpd:2.4"
    ports:
      - "80:80"

    volumes:
      - ./htdocs/public:/var/www/html/public:ro
      #datei ersetzt andere Datei nach dem Doppelpunkt
      - ./docker/container/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      - ./docker/container/httpd/vhost.conf:/usr/local/apache2/conf/vhost.conf:ro
    depends_on:
      - php

  php:
    #anstatt standard image baue eigenes
    build: docker/container/php
    volumes:
      - ./htdocs:/var/www/html
    depends_on:
      - db
  db:
    image: mariadb
    volumes:
      - ./.var/mysql:/var/lib/mysql
    ports:
      #außen:innen
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tin
      MYSQL_USER: tin
      MYSQL_PASSWORD: tin
  selenium:
    image: selenium/standalone-chrome:3
    shm_size: '2gb'
    # other possible images
    #image: selenium/standalone-chrome-debug:3
    #image: selenium/standalone-firefox:3
    #image: selenium/standalone-firefox-debug:3
    #image: selenium/node-phantomjs:3
    environment:
      - VIRTUAL_HOST=www.blog.priv
      - HTTP_EXPOSE=4444
    networks:
      - default
    depends_on:
      - www.blog.priv
  encore:
    image: node:10-alpine
    volumes:
      - ./htdocs:/var/www/html
    ports:
      - "${DEV_SERVER_PORT:-8080}:8080"
    working_dir: /var/www/html
    command: ["yarn", "dev-server", "--host=0.0.0.0"]

